2024-05-14 14:07:54,790 INFO    StreamThr :921833 [internal.py:wandb_internal():86] W&B internal server running at pid: 921833, started at: 2024-05-14 14:07:54.789860
2024-05-14 14:07:54,792 DEBUG   HandlerThread:921833 [handler.py:handle_request():146] handle_request: status
2024-05-14 14:07:54,819 INFO    WriterThread:921833 [datastore.py:open_for_write():85] open: /nfs/datx/lyk/HiFT/wandb/run-20240514_140754-1xykd35d/run-1xykd35d.wandb
2024-05-14 14:07:54,820 DEBUG   SenderThread:921833 [sender.py:send():382] send: header
2024-05-14 14:07:54,820 DEBUG   SenderThread:921833 [sender.py:send():382] send: run
2024-05-14 14:07:55,193 INFO    SenderThread:921833 [dir_watcher.py:__init__():211] watching files in: /nfs/datx/lyk/HiFT/wandb/run-20240514_140754-1xykd35d/files
2024-05-14 14:07:55,193 INFO    SenderThread:921833 [sender.py:_start_run_threads():1136] run started: 1xykd35d with start time 1715688474.81498
2024-05-14 14:07:55,201 DEBUG   HandlerThread:921833 [handler.py:handle_request():146] handle_request: check_version
2024-05-14 14:07:55,202 DEBUG   SenderThread:921833 [sender.py:send_request():409] send_request: check_version
2024-05-14 14:07:55,263 DEBUG   HandlerThread:921833 [handler.py:handle_request():146] handle_request: run_start
2024-05-14 14:07:55,300 DEBUG   HandlerThread:921833 [system_info.py:__init__():32] System info init
2024-05-14 14:07:55,300 DEBUG   HandlerThread:921833 [system_info.py:__init__():47] System info init done
2024-05-14 14:07:55,300 INFO    HandlerThread:921833 [system_monitor.py:start():194] Starting system monitor
2024-05-14 14:07:55,301 INFO    SystemMonitor:921833 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-05-14 14:07:55,302 INFO    HandlerThread:921833 [system_monitor.py:probe():214] Collecting system info
2024-05-14 14:07:55,303 INFO    SystemMonitor:921833 [interfaces.py:start():190] Started cpu monitoring
2024-05-14 14:07:55,303 INFO    SystemMonitor:921833 [interfaces.py:start():190] Started disk monitoring
2024-05-14 14:07:55,304 INFO    SystemMonitor:921833 [interfaces.py:start():190] Started gpu monitoring
2024-05-14 14:07:55,305 INFO    SystemMonitor:921833 [interfaces.py:start():190] Started memory monitoring
2024-05-14 14:07:55,306 INFO    SystemMonitor:921833 [interfaces.py:start():190] Started network monitoring
2024-05-14 14:07:55,388 DEBUG   HandlerThread:921833 [system_info.py:probe():196] Probing system
2024-05-14 14:07:55,393 DEBUG   HandlerThread:921833 [gitlib.py:_init_repo():56] git repository is invalid
2024-05-14 14:07:55,393 DEBUG   HandlerThread:921833 [system_info.py:probe():244] Probing system done
2024-05-14 14:07:55,393 DEBUG   HandlerThread:921833 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-91-generic-x86_64-with-glibc2.10', 'python': '3.8.5', 'heartbeatAt': '2024-05-14T12:07:55.388311', 'startedAt': '2024-05-14T12:07:54.762202', 'docker': None, 'cuda': None, 'args': ('--model_type', 'llama', '--HiTaskType', 'CAUSAL_LM', '--optim', 'rmsprop_32bit', '--deepspeed', 'dsconfig/zero0_config.json', '--model_name_or_path', '/mounts/work/lyk/hierFT/llama2-7b', '--dataset_dir', 'data/alpaca_data', '--validation_split_percentage', '0.01', '--per_device_train_batch_size', '12', '--per_device_eval_batch_size', '8', '--do_train', '--do_eval', '--seed', '12345', '--fp16', '--tf32', 'true', '--num_train_epochs', '1', '--lr_scheduler_type', 'cosine', '--learning_rate', '2e-5', '--warmup_ratio', '0.03', '--weight_decay', '0.0', '--logging_strategy', 'steps', '--logging_steps', '10', '--save_strategy', 'steps', '--save_total_limit', '3', '--evaluation_strategy', 'steps', '--eval_steps', '100', '--save_steps', '200', '--preprocessing_num_workers', '4', '--max_seq_length', '512', '--output_dir', 'outputs/instruct_tuning/model', '--overwrite_output_dir', '--logging_first_step', 'True', '--torch_dtype', 'float16', '--ddp_find_unused_parameters', 'False', '--load_best_model_at_end', '--hier_tuning', '--group_element', '1', '--optimizer_strategy', 'down2up'), 'state': 'running', 'program': 'examples/instruct_tuning.py', 'codePathLocal': 'examples/instruct_tuning.py', 'codePath': 'examples/instruct_tuning.py', 'host': 'rho1', 'username': 'yongkang', 'executable': '/mounts/work/lyk/anaconda3/envs/torch2/bin/python', 'cpu_count': 32, 'cpu_count_logical': 64, 'cpu_freq': {'current': 1896.107453125, 'min': 1500.0, 'max': 3000.0}, 'cpu_freq_per_core': [{'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 2200.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3709.643, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 2200.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3723.077, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 2200.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 2200.0, 'min': 1500.0, 'max': 3000.0}, {'current': 2200.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1924.496, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3710.324, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 2200.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}], 'disk': {'/': {'total': 878.1072120666504, 'used': 583.3433380126953}}, 'gpu': 'NVIDIA RTX A6000', 'gpu_count': 8, 'gpu_devices': [{'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}], 'memory': {'total': 251.73123168945312}}
2024-05-14 14:07:55,394 INFO    HandlerThread:921833 [system_monitor.py:probe():224] Finished collecting system info
2024-05-14 14:07:55,394 INFO    HandlerThread:921833 [system_monitor.py:probe():227] Publishing system info
2024-05-14 14:07:55,394 DEBUG   HandlerThread:921833 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-05-14 14:07:55,395 DEBUG   HandlerThread:921833 [system_info.py:_save_pip():68] Saving pip packages done
2024-05-14 14:07:55,395 DEBUG   HandlerThread:921833 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-05-14 14:07:56,195 INFO    Thread-12 :921833 [dir_watcher.py:_on_file_created():271] file/dir created: /nfs/datx/lyk/HiFT/wandb/run-20240514_140754-1xykd35d/files/requirements.txt
2024-05-14 14:07:56,196 INFO    Thread-12 :921833 [dir_watcher.py:_on_file_created():271] file/dir created: /nfs/datx/lyk/HiFT/wandb/run-20240514_140754-1xykd35d/files/conda-environment.yaml
2024-05-14 14:08:03,315 INFO    cpu       :921833 [interfaces.py:monitor():140] Process cpu has exited.
2024-05-14 14:08:03,316 DEBUG   SystemMonitor:921833 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-05-14 14:08:03,316 DEBUG   SystemMonitor:921833 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-05-14 14:08:03,316 DEBUG   SystemMonitor:921833 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-05-14 14:08:03,319 INFO    memory    :921833 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2024-05-14 14:08:03,437 DEBUG   HandlerThread:921833 [system_info.py:_save_conda():87] Saving conda packages done
2024-05-14 14:08:03,451 INFO    HandlerThread:921833 [system_monitor.py:probe():229] Finished publishing system info
2024-05-14 14:08:03,476 DEBUG   HandlerThread:921833 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:08:03,476 DEBUG   HandlerThread:921833 [handler.py:handle_request():146] handle_request: keepalive
2024-05-14 14:08:03,478 DEBUG   SenderThread:921833 [sender.py:send():382] send: stats
2024-05-14 14:08:03,479 DEBUG   SenderThread:921833 [sender.py:send():382] send: files
2024-05-14 14:08:03,479 INFO    SenderThread:921833 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-05-14 14:08:03,802 WARNING StreamThr :921833 [internal.py:is_dead():414] Internal process exiting, parent pid 921424 disappeared
2024-05-14 14:08:03,802 ERROR   StreamThr :921833 [internal.py:wandb_internal():152] Internal process shutdown.
2024-05-14 14:08:03,905 ERROR   wandb-upload_0:921833 [internal_api.py:upload_file():2761] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/1xykd35d/wandb-metadata.json?Expires=1715774883&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uF%2FAU9cbwNBOR4kFxXM9p2gTvPkmz%2FCgh5Cb2%2FVgXfAGJCna%2FbjY7BqtE3HJkvZBgbT8sr10wm8lYrHbrjjPK0nqTdg%2F%2Byg7pRQ21v9L%2FxaLDsZBfQqftGYffkL3BT%2F3uahzH7wOL8eIaf04wOdzXN7z7FCxCbn38WmZDeDvDj2EhaVnHX7glw6Yo9KdGxwG4XTa8Hu0ThFkYOY6Tyw5QET5MfC5Uiq9yhORfIJC3bmaKzVN2LvWf%2BPCK3dVeH1eY4b7wrBVBU7cVvmHkIOsfkGMVUdvtoGBhXKU%2Fz3LLMSUHXC1iWD1G7drcXuTfy%2Fc0WrULS%2BfuCGB%2BMsux0OENg%3D%3D: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/1xykd35d/wandb-metadata.json?Expires=1715774883&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uF%2FAU9cbwNBOR4kFxXM9p2gTvPkmz%2FCgh5Cb2%2FVgXfAGJCna%2FbjY7BqtE3HJkvZBgbT8sr10wm8lYrHbrjjPK0nqTdg%2F%2Byg7pRQ21v9L%2FxaLDsZBfQqftGYffkL3BT%2F3uahzH7wOL8eIaf04wOdzXN7z7FCxCbn38WmZDeDvDj2EhaVnHX7glw6Yo9KdGxwG4XTa8Hu0ThFkYOY6Tyw5QET5MfC5Uiq9yhORfIJC3bmaKzVN2LvWf%2BPCK3dVeH1eY4b7wrBVBU7cVvmHkIOsfkGMVUdvtoGBhXKU%2Fz3LLMSUHXC1iWD1G7drcXuTfy%2Fc0WrULS%2BfuCGB%2BMsux0OENg%3D%3D
2024-05-14 14:08:03,905 ERROR   wandb-upload_0:921833 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '10144'}
2024-05-14 14:08:03,905 ERROR   wandb-upload_0:921833 [internal_api.py:upload_file():2765] upload_file response body: b"<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>We're sorry, but this service is not available in your location</Details></Error>"
2024-05-14 14:08:03,969 ERROR   wandb-upload_0:921833 [upload_job.py:push():134] Failed to upload file: /tmp/tmpu4e_yjqywandb/rl5cvjti-wandb-metadata.json
Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2787, in upload_file
    wandb._sentry.reraise(e)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/1xykd35d/wandb-metadata.json?Expires=1715774883&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uF%2FAU9cbwNBOR4kFxXM9p2gTvPkmz%2FCgh5Cb2%2FVgXfAGJCna%2FbjY7BqtE3HJkvZBgbT8sr10wm8lYrHbrjjPK0nqTdg%2F%2Byg7pRQ21v9L%2FxaLDsZBfQqftGYffkL3BT%2F3uahzH7wOL8eIaf04wOdzXN7z7FCxCbn38WmZDeDvDj2EhaVnHX7glw6Yo9KdGxwG4XTa8Hu0ThFkYOY6Tyw5QET5MfC5Uiq9yhORfIJC3bmaKzVN2LvWf%2BPCK3dVeH1eY4b7wrBVBU7cVvmHkIOsfkGMVUdvtoGBhXKU%2Fz3LLMSUHXC1iWD1G7drcXuTfy%2Fc0WrULS%2BfuCGB%2BMsux0OENg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 125, in push
    self._api.upload_file_retry(
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [403]>
2024-05-14 14:08:03,993 ERROR   Thread-11 :921833 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpu4e_yjqywandb/rl5cvjti-wandb-metadata.json
Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2787, in upload_file
    wandb._sentry.reraise(e)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/1xykd35d/wandb-metadata.json?Expires=1715774883&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uF%2FAU9cbwNBOR4kFxXM9p2gTvPkmz%2FCgh5Cb2%2FVgXfAGJCna%2FbjY7BqtE3HJkvZBgbT8sr10wm8lYrHbrjjPK0nqTdg%2F%2Byg7pRQ21v9L%2FxaLDsZBfQqftGYffkL3BT%2F3uahzH7wOL8eIaf04wOdzXN7z7FCxCbn38WmZDeDvDj2EhaVnHX7glw6Yo9KdGxwG4XTa8Hu0ThFkYOY6Tyw5QET5MfC5Uiq9yhORfIJC3bmaKzVN2LvWf%2BPCK3dVeH1eY4b7wrBVBU7cVvmHkIOsfkGMVUdvtoGBhXKU%2Fz3LLMSUHXC1iWD1G7drcXuTfy%2Fc0WrULS%2BfuCGB%2BMsux0OENg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 125, in push
    self._api.upload_file_retry(
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [403]>
2024-05-14 14:08:04,201 INFO    Thread-12 :921833 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_140754-1xykd35d/files/conda-environment.yaml
2024-05-14 14:08:04,202 INFO    Thread-12 :921833 [dir_watcher.py:_on_file_created():271] file/dir created: /nfs/datx/lyk/HiFT/wandb/run-20240514_140754-1xykd35d/files/wandb-metadata.json
2024-05-14 14:08:04,265 INFO    MainThread:921833 [internal.py:handle_exit():76] Internal process exited
